/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Department = { 'marketing' : null } |
  { 'store' : null } |
  { 'purchase' : null };
export interface Task {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'mode' : TaskMode,
  'description' : TaskDescription,
  'department' : Department,
}
export type TaskDescription = string;
export type TaskId = bigint;
export type TaskMode = { 'onSite' : null } |
  { 'online' : null };
export type TaskStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  'addTask' : ActorMethod<
    [TaskId, string, string, Department, TaskMode],
    undefined
  >,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getDepartmentMap' : ActorMethod<[], Array<[string, Department]>>,
  'getModeMap' : ActorMethod<[], Array<[string, TaskMode]>>,
  'getStatusMap' : ActorMethod<[], Array<[string, TaskStatus]>>,
  'getTasks' : ActorMethod<[[] | [string], [] | [string]], Array<Task>>,
  'updateTaskStatus' : ActorMethod<[TaskId, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];