/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskId = IDL.Nat;
export const Department = IDL.Variant({
  'marketing' : IDL.Null,
  'store' : IDL.Null,
  'purchase' : IDL.Null,
});
export const TaskMode = IDL.Variant({
  'onSite' : IDL.Null,
  'online' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskDescription = IDL.Text;
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'mode' : TaskMode,
  'description' : TaskDescription,
  'department' : Department,
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, Department, TaskMode],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getDepartmentMap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Department))],
      ['query'],
    ),
  'getModeMap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TaskMode))],
      ['query'],
    ),
  'getStatusMap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TaskStatus))],
      ['query'],
    ),
  'getTasks' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskId = IDL.Nat;
  const Department = IDL.Variant({
    'marketing' : IDL.Null,
    'store' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const TaskMode = IDL.Variant({ 'onSite' : IDL.Null, 'online' : IDL.Null });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskDescription = IDL.Text;
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'mode' : TaskMode,
    'description' : TaskDescription,
    'department' : Department,
  });
  
  return IDL.Service({
    'addTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, Department, TaskMode],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getDepartmentMap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Department))],
        ['query'],
      ),
    'getModeMap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TaskMode))],
        ['query'],
      ),
    'getStatusMap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TaskStatus))],
        ['query'],
      ),
    'getTasks' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };