/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: TaskId;
    status: TaskStatus;
    title: string;
    mode: TaskMode;
    description: TaskDescription;
    department: Department;
}
export type TaskDescription = string;
export type TaskId = bigint;
export enum Department {
    marketing = "marketing",
    store = "store",
    purchase = "purchase"
}
export enum TaskMode {
    onSite = "onSite",
    online = "online"
}
export enum TaskStatus {
    pending = "pending",
    done = "done",
    inProgress = "inProgress"
}
export interface backendInterface {
    addTask(taskId: TaskId, title: string, description: string, departmentBalloon: Department, modeBalloon: TaskMode): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    getDepartmentMap(): Promise<Array<[string, Department]>>;
    getModeMap(): Promise<Array<[string, TaskMode]>>;
    getStatusMap(): Promise<Array<[string, TaskStatus]>>;
    getTasks(departmentText: string | null, modeText: string | null): Promise<Array<Task>>;
    updateTaskStatus(taskId: TaskId, newStatus: TaskStatus): Promise<void>;
}
import type { Department as _Department, Task as _Task, TaskDescription as _TaskDescription, TaskId as _TaskId, TaskMode as _TaskMode, TaskStatus as _TaskStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTask(arg0: TaskId, arg1: string, arg2: string, arg3: Department, arg4: TaskMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1, arg2, to_candid_Department_n1(this._uploadFile, this._downloadFile, arg3), to_candid_TaskMode_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1, arg2, to_candid_Department_n1(this._uploadFile, this._downloadFile, arg3), to_candid_TaskMode_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getDepartmentMap(): Promise<Array<[string, Department]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartmentMap();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartmentMap();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModeMap(): Promise<Array<[string, TaskMode]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModeMap();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModeMap();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatusMap(): Promise<Array<[string, TaskStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatusMap();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatusMap();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: string | null, arg1: string | null): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTaskStatus(arg0: TaskId, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Department_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TaskMode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskMode): TaskMode {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    mode: _TaskMode;
    description: _TaskDescription;
    department: _Department;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    mode: TaskMode;
    description: TaskDescription;
    department: Department;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        mode: from_candid_TaskMode_n11(_uploadFile, _downloadFile, value.mode),
        description: value.description,
        department: from_candid_Department_n7(_uploadFile, _downloadFile, value.department)
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _TaskMode]): [string, TaskMode] {
    return [
        value[0],
        from_candid_TaskMode_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _TaskStatus]): [string, TaskStatus] {
    return [
        value[0],
        from_candid_TaskStatus_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Department]): [string, Department] {
    return [
        value[0],
        from_candid_Department_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onSite: null;
} | {
    online: null;
}): TaskMode {
    return "onSite" in value ? TaskMode.onSite : "online" in value ? TaskMode.online : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "done" in value ? TaskStatus.done : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketing: null;
} | {
    store: null;
} | {
    purchase: null;
}): Department {
    return "marketing" in value ? Department.marketing : "store" in value ? Department.store : "purchase" in value ? Department.purchase : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _TaskStatus]>): Array<[string, TaskStatus]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Department]>): Array<[string, Department]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _TaskMode]>): Array<[string, TaskMode]> {
    return value.map((x)=>from_candid_tuple_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Department_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TaskMode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskMode): _TaskMode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    marketing: null;
} | {
    store: null;
} | {
    purchase: null;
} {
    return value == Department.marketing ? {
        marketing: null
    } : value == Department.store ? {
        store: null
    } : value == Department.purchase ? {
        purchase: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    done: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.done ? {
        done: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskMode): {
    onSite: null;
} | {
    online: null;
} {
    return value == TaskMode.onSite ? {
        onSite: null
    } : value == TaskMode.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
